#!/usr/bin/env bash
# redirecting Nginx server to another page

redirect_url='https://www.youtube.com'

#sudo apt-get update -y
#sudo apt-get install nginx -y

# Create a custom HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.htmt

sudo sed -i "37i\ \n\tlocation /redirect_me {\n\t\treturn 301 $redirect_url; \n\t}\n" /etc/nginx/sites-available/default

# Restart Nginx (without systemctl)
sudo /etc/init.d/nginx restart
