#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

oldstr="=404;"
newstr="@bad_address ;\n\t}\n\n\tlocation @bad_address {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n\'est pas une page\";"

sudo sed -i -z "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

sudo service nginx restart
