#!/usr/bin/env bash
#this script displays numbers from 1 to 100 with:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number

count=0
while [ $count -lt 100 ]; do
	(( count+=1 ))
	if (( count % 3 == 0 )) && (( count % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( count % 3 == 0 )); then
		echo "Fizz"
	elif ((  count % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$count"
	fi
done
