#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and
#+	displays 4 and then bad luck from China for the 4th loop iteration
#+	displays 9 and then bad luck from Japan for the 9th loop iteration
#+	displays 17 and then bad luck from Italy for the 17th loop iteration

i=1
while ((i <= 20))
do
case "$i" in
	4)
		echo "bad luck from China"
		echo "$i"
		;;
	9)
		echo "bad luck from Japan"
		echo "$i"
		;;
	17)
		echo "bad luck from Italy"
		echo "$i"
		;;
	*)
		echo "$i"
		;;
	esac
	((i++))
done

