#!/usr/bin/env bash
#this script will displays the time for 12 hours and 59 minutes

hour=0

while [ "$hour" -le 12 ]
do
	echo "hour: $hour"
	for ((minute=0; minute <=59; minute++))
	do
		echo "$minute"
	done
	((hour++))
done
