#!/usr/bin/env bash

# this script displays:
#	- The content of the current directory
#	- In a list format
#	- Where only the part of the name after the first dash is displayed

content=$(ls)
for file in "$content"
do
	echo "$file" | cut -d "-" -f 2
done
