#!/usr/bin/env bash

# this script displays:
#	- The content of the current directory
#	- In a list format
#	- Where only the part of the name after the first dash is displayed

content=$(ls)
for f in $content
do
	echo "$f" | cut -d'-' -f 2
done
